package growzapp.backend.model.enumeration;

public enum TypeTransaction {
    DEPOT,
    RETRAIT,
    TRANSFER_OUT,
    TRANSFER_IN,
    INVESTISSEMENT,
    PAIEMENT_STRIPE,
    PAIEMENT_OM,
    PAIEMENT_MTN,
    PAIEMENT_WAVE,
    REMBOURSEMENT,

    // NOUVEAU : RETRAITS RÉELS
    PAYOUT_OM,
    PAYOUT_MTN,
    PAYOUT_WAVE,
    PAYOUT_OM_SN,
    PAYOUT_WAVE_SN,
    PAYOUT_MOOV,
    PAYOUT_STRIPE,
    PAYOUT_BANK,


    CREDIT_PROJET,
    VIREMENT_PORTEUR,
    RETRAIT_MOBILE_MONEY,

    VERSEMENT_PORTEUR,
    VERSEMENT_DIVIDENDE, DIVIDENDE_ENTRANT, DIVIDENDE_SORTANT, DIVIDENDE, RETRAIT_ADMIN
}