-- Remplace la traduction du secteur au niveau projet (V15, dupliquée pour
-- chaque projet du même secteur) par une traduction partagée au niveau du
-- secteur lui-même : traduite une seule fois, réutilisée par tous les
-- projets de ce secteur.
CREATE TABLE secteur_traductions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    secteur_id BIGINT NOT NULL REFERENCES secteurs(id),
    langue VARCHAR(5) NOT NULL,
    nom VARCHAR(150),
    CONSTRAINT uk_secteur_traduction_secteur_langue UNIQUE (secteur_id, langue)
);

ALTER TABLE projet_traductions DROP COLUMN secteur_nom;
