--
-- PostgreSQL database dump
--


-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1


--
-- Name: unaccent; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;


--
-- Name: EXTENSION unaccent; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION unaccent IS 'text search dictionary that removes accents';




--
-- Name: contrats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contrats (
    id bigint NOT NULL,
    date_generation timestamp(6) without time zone,
    fichier_url character varying(255),
    lien_verification character varying(255),
    numero_contrat character varying(255) NOT NULL,
    investissement_id bigint,
    hash_sha256 character varying(255),
    token_verification character varying(255)
);


--
-- Name: contrats_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contrats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contrats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dividendes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dividendes (
    id bigint NOT NULL,
    date_paiement timestamp(6) without time zone,
    montant_par_part numeric(15,2),
    motif character varying(255),
    moyen_paiement character varying(255),
    statut_dividende character varying(255),
    investissement_id bigint NOT NULL,
    CONSTRAINT dividendes_moyen_paiement_check CHECK (((moyen_paiement)::text = ANY ((ARRAY['VIREMENT'::character varying, 'CARTE'::character varying, 'MOBILE_MONEY'::character varying, 'ORANGE_MONEY'::character varying, 'WAVE'::character varying, 'CRYPTO'::character varying, 'WALLET'::character varying])::text[]))),
    CONSTRAINT dividendes_statut_dividende_check CHECK (((statut_dividende)::text = ANY ((ARRAY['PLANIFIE'::character varying, 'PAYE'::character varying, 'ANNULE'::character varying])::text[])))
);


--
-- Name: dividendes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dividendes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dividendes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents (
    id bigint NOT NULL,
    filename character varying(255) NOT NULL,
    nom character varying(255),
    type character varying(20) NOT NULL,
    uploaded_at timestamp(6) without time zone,
    projet_id bigint
);


--
-- Name: documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employe_fonctions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employe_fonctions (
    date_prise_fonction date NOT NULL,
    employe_id bigint NOT NULL,
    fonction_id bigint NOT NULL
);


--
-- Name: employes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employes (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    nom character varying(255) NOT NULL,
    prenom character varying(255) NOT NULL,
    telephone character varying(255)
);


--
-- Name: employes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exchange_rate; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exchange_rate (
    currency_code character varying(255) NOT NULL,
    last_updated timestamp(6) without time zone,
    rate_to_base numeric(38,2)
);


--
-- Name: factures; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.factures (
    id bigint NOT NULL,
    date_emission timestamp(6) without time zone,
    date_paiement timestamp(6) without time zone,
    fichier_url character varying(255),
    montant_ht double precision,
    montant_ttc double precision,
    numero_facture character varying(100) NOT NULL,
    statut character varying(255),
    tva double precision,
    dividende_id bigint NOT NULL,
    investisseur_id bigint NOT NULL,
    CONSTRAINT factures_statut_check CHECK (((statut)::text = ANY ((ARRAY['EMISE'::character varying, 'PAYEE'::character varying, 'ANNULEE'::character varying, 'EN_RETARD'::character varying])::text[])))
);


--
-- Name: factures_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.factures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.factures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fonctions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fonctions (
    id bigint NOT NULL,
    description character varying(255),
    nom character varying(255) NOT NULL
);


--
-- Name: fonctions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fonctions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fonctions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: investissements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.investissements (
    id bigint NOT NULL,
    date timestamp(6) without time zone NOT NULL,
    frais double precision NOT NULL,
    montant_investi numeric(38,2) NOT NULL,
    nombre_parts_pris integer NOT NULL,
    statut_investissement character varying(255) NOT NULL,
    pourcent_equity double precision NOT NULL,
    user_id bigint NOT NULL,
    projet_id bigint NOT NULL,
    insurance_terms_accepted_at timestamp(6) without time zone,
    risk_warning_accepted_at timestamp(6) without time zone,
    reference_externe_stripe character varying(255),
    CONSTRAINT investissements_statut_investissement_check CHECK (((statut_investissement)::text = ANY ((ARRAY['EN_ATTENTE'::character varying, 'VALIDE'::character varying, 'ANNULE'::character varying, 'REMBOURSE'::character varying])::text[])))
);


--
-- Name: investissements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.investissements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.investissements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: langues; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.langues (
    id bigint NOT NULL,
    nom character varying(255)
);


--
-- Name: langues_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.langues ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.langues_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: localisations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.localisations (
    id bigint NOT NULL,
    adresse character varying(255),
    contact character varying(255),
    created_at timestamp(6) without time zone,
    nom character varying(255),
    responsable character varying(255),
    localite_id bigint,
    latitude numeric(10,8),
    longitude numeric(11,8),
    what3words character varying(255)
);


--
-- Name: localisations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.localisations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.localisations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: localites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.localites (
    id bigint NOT NULL,
    code_postal character varying(255),
    nom character varying(255),
    pays_id bigint
);


--
-- Name: localites_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.localites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.localites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.news (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    image_url character varying(255),
    title character varying(255) NOT NULL,
    CONSTRAINT news_category_check CHECK (((category)::text = ANY ((ARRAY['PLATFORM_UPDATE'::character varying, 'INVESTMENT_OPPORTUNITY'::character varying, 'PERFORMANCE_REPORT'::character varying, 'EDUCATION'::character varying, 'SECURITY'::character varying])::text[])))
);


--
-- Name: news_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    content character varying(255),
    date timestamp(6) without time zone,
    is_read boolean NOT NULL,
    title character varying(255),
    user_id bigint
);


--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    content text,
    date timestamp(6) without time zone,
    is_read boolean NOT NULL,
    title character varying(255),
    user_id bigint,
    projet_id bigint,
    projet_slug character varying(255),
    motif text,
    facture_id bigint
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payouts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payouts (
    id bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    external_payout_id character varying(255),
    montant numeric(38,2),
    motif_echec character varying(255),
    paydunya_invoice_url character varying(255),
    paydunya_status character varying(255),
    paydunya_token character varying(255),
    statut character varying(255),
    type character varying(255),
    user_id bigint,
    user_login character varying(255),
    user_phone character varying(255),
    CONSTRAINT payouts_statut_check CHECK (((statut)::text = ANY ((ARRAY['EN_COURS'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'EN_ATTENTE_VALIDATION'::character varying, 'REJETEE'::character varying, 'EN_ATTENTE_PAIEMENT'::character varying, 'PAYE'::character varying, 'ECHEC_PAIEMENT'::character varying])::text[]))),
    CONSTRAINT payouts_type_check CHECK (((type)::text = ANY ((ARRAY['DEPOT'::character varying, 'RETRAIT'::character varying, 'TRANSFER_OUT'::character varying, 'TRANSFER_IN'::character varying, 'INVESTISSEMENT'::character varying, 'PAIEMENT_STRIPE'::character varying, 'PAIEMENT_OM'::character varying, 'PAIEMENT_MTN'::character varying, 'PAIEMENT_WAVE'::character varying, 'REMBOURSEMENT'::character varying, 'PAYOUT_OM'::character varying, 'PAYOUT_MTN'::character varying, 'PAYOUT_WAVE'::character varying, 'PAYOUT_OM_SN'::character varying, 'PAYOUT_WAVE_SN'::character varying, 'PAYOUT_MOOV'::character varying, 'PAYOUT_STRIPE'::character varying, 'PAYOUT_BANK'::character varying, 'CREDIT_PROJET'::character varying, 'VIREMENT_PORTEUR'::character varying, 'RETRAIT_MOBILE_MONEY'::character varying, 'VERSEMENT_PORTEUR'::character varying, 'VERSEMENT_DIVIDENDE'::character varying, 'DIVIDENDE_ENTRANT'::character varying, 'DIVIDENDE_SORTANT'::character varying, 'DIVIDENDE'::character varying, 'RETRAIT_ADMIN'::character varying])::text[])))
);


--
-- Name: payouts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payouts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payouts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pays; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pays (
    id bigint NOT NULL,
    nom character varying(255)
);


--
-- Name: pays_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pays ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pays_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personal_access_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personal_access_tokens (
    id bigint NOT NULL,
    expires_at timestamp(6) without time zone,
    token character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: personal_access_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personal_access_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personal_access_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projet_traductions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projet_traductions (
    id bigint NOT NULL,
    description text,
    langue character varying(5) NOT NULL,
    libelle character varying(200),
    projet_id bigint NOT NULL
);


--
-- Name: projet_traductions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.projet_traductions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projet_traductions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projet_valorisations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projet_valorisations (
    id bigint NOT NULL,
    date_snapshot timestamp(6) without time zone,
    montant_collecte numeric(38,2),
    montant_evenement numeric(38,2),
    montant_valorisation numeric(38,2),
    type_evenement character varying(30) NOT NULL,
    projet_id bigint NOT NULL,
    CONSTRAINT projet_valorisations_type_evenement_check CHECK (((type_evenement)::text = ANY ((ARRAY['CREATION'::character varying, 'VALIDATION'::character varying, 'INVESTISSEMENT'::character varying, 'DIVIDENDE'::character varying, 'REEVALUATION'::character varying])::text[])))
);


--
-- Name: projet_valorisations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.projet_valorisations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projet_valorisations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projets (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    financement_debut date,
    financement_fin date,
    description character varying(255),
    duree_mois integer NOT NULL,
    libelle character varying(255),
    montant_collecte numeric(38,2),
    objectif_financement numeric(38,2),
    parts_disponible integer,
    parts_prises integer,
    poster character varying(255),
    prix_une_part numeric(38,2),
    reference integer,
    roi_projete double precision NOT NULL,
    statut_projet character varying(255),
    valeur_totale_parts_en_pourcent double precision NOT NULL,
    valuation numeric(38,2),
    user_id bigint,
    secteur_id bigint,
    site_id bigint,
    slug character varying(255),
    anti_fraud_declaration_at timestamp(6) without time zone,
    certified_at timestamp(6) without time zone,
    porteur_id bigint,
    CONSTRAINT projets_duree_mois_check CHECK ((duree_mois >= 1)),
    CONSTRAINT projets_objectif_financement_check CHECK ((objectif_financement >= (0)::numeric)),
    CONSTRAINT projets_parts_disponible_check CHECK ((parts_disponible >= 0)),
    CONSTRAINT projets_prix_une_part_check CHECK ((prix_une_part >= (0)::numeric)),
    CONSTRAINT projets_statut_projet_check CHECK (((statut_projet)::text = ANY ((ARRAY['EN_PREPARATION'::character varying, 'SOUMIS'::character varying, 'VALIDE'::character varying, 'REJETE'::character varying, 'EN_COURS'::character varying, 'TERMINE'::character varying, 'EN_ATTENTE'::character varying])::text[])))
);


--
-- Name: projets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.projets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    role character varying(255) NOT NULL
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: secteurs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.secteurs (
    id bigint NOT NULL,
    nom character varying(255)
);


--
-- Name: secteurs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.secteurs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.secteurs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(500),
    montant numeric(15,2) NOT NULL,
    reference_externe character varying(255),
    reference_id bigint,
    reference_type character varying(50),
    statut character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    wallet_id bigint NOT NULL,
    wallet_type character varying(255) NOT NULL,
    destinataire_wallet_id bigint,
    CONSTRAINT transactions_statut_check CHECK (((statut)::text = ANY ((ARRAY['EN_COURS'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'EN_ATTENTE_VALIDATION'::character varying, 'REJETEE'::character varying, 'EN_ATTENTE_PAIEMENT'::character varying, 'PAYE'::character varying, 'ECHEC_PAIEMENT'::character varying])::text[]))),
    CONSTRAINT transactions_type_check CHECK (((type)::text = ANY ((ARRAY['DEPOT'::character varying, 'RETRAIT'::character varying, 'TRANSFER_OUT'::character varying, 'TRANSFER_IN'::character varying, 'INVESTISSEMENT'::character varying, 'PAIEMENT_STRIPE'::character varying, 'PAIEMENT_OM'::character varying, 'PAIEMENT_MTN'::character varying, 'PAIEMENT_WAVE'::character varying, 'REMBOURSEMENT'::character varying, 'PAYOUT_OM'::character varying, 'PAYOUT_MTN'::character varying, 'PAYOUT_WAVE'::character varying, 'PAYOUT_OM_SN'::character varying, 'PAYOUT_WAVE_SN'::character varying, 'PAYOUT_MOOV'::character varying, 'PAYOUT_STRIPE'::character varying, 'PAYOUT_BANK'::character varying, 'CREDIT_PROJET'::character varying, 'VIREMENT_PORTEUR'::character varying, 'RETRAIT_MOBILE_MONEY'::character varying, 'VERSEMENT_PORTEUR'::character varying, 'VERSEMENT_DIVIDENDE'::character varying, 'DIVIDENDE_ENTRANT'::character varying, 'DIVIDENDE_SORTANT'::character varying, 'DIVIDENDE'::character varying, 'RETRAIT_ADMIN'::character varying])::text[]))),
    CONSTRAINT transactions_wallet_type_check CHECK (((wallet_type)::text = ANY ((ARRAY['USER'::character varying, 'PROJET'::character varying, 'DIVIDENDE'::character varying])::text[])))
);


--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_langues; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_langues (
    user_id bigint NOT NULL,
    langue_id bigint NOT NULL
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    contact character varying(255),
    email character varying(191),
    enabled boolean NOT NULL,
    image character varying(255),
    interface_language character varying(5),
    login character varying(50) NOT NULL,
    nom character varying(255),
    password character varying(255) NOT NULL,
    prenom character varying(255),
    sexe character(1),
    stripe_account_id character varying(100),
    localite_id bigint,
    kyc_status character varying(20) DEFAULT 'NON_SOUMIS'::character varying,
    kyc_document_url character varying(255),
    date_naissance date,
    adresse_residencielle character varying(255),
    kyc_date_validation timestamp without time zone,
    kyc_commentaire_rejet character varying(255),
    kyc_date_delivrance date,
    kyc_date_expiration date,
    kyc_numero_piece character varying(50),
    kyc_recto_url character varying(255),
    kyc_selfie_url character varying(255),
    kyc_verso_url character varying(255),
    cgu_accepted_at timestamp(6) without time zone,
    cgu_version_accepted character varying(255),
    rgpd_accepted_at timestamp(6) without time zone,
    devise_preferee character varying(10),
    CONSTRAINT users_sexe_check CHECK ((sexe = ANY (ARRAY['M'::bpchar, 'F'::bpchar, 'X'::bpchar])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wallets (
    id bigint NOT NULL,
    projet_id bigint,
    solde_bloque numeric(18,2) NOT NULL,
    solde_disponible numeric(18,2) NOT NULL,
    solde_retirable numeric(18,2) NOT NULL,
    wallet_type character varying(255) NOT NULL,
    user_id bigint,
    CONSTRAINT wallets_wallet_type_check CHECK (((wallet_type)::text = ANY ((ARRAY['USER'::character varying, 'PROJET'::character varying, 'DIVIDENDE'::character varying])::text[])))
);


--
-- Name: wallets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wallets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contrats contrats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contrats
    ADD CONSTRAINT contrats_pkey PRIMARY KEY (id);


--
-- Name: dividendes dividendes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dividendes
    ADD CONSTRAINT dividendes_pkey PRIMARY KEY (id);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);


--
-- Name: employe_fonctions employe_fonctions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employe_fonctions
    ADD CONSTRAINT employe_fonctions_pkey PRIMARY KEY (employe_id, fonction_id);


--
-- Name: employes employes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employes
    ADD CONSTRAINT employes_pkey PRIMARY KEY (id);


--
-- Name: exchange_rate exchange_rate_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exchange_rate
    ADD CONSTRAINT exchange_rate_pkey PRIMARY KEY (currency_code);


--
-- Name: factures factures_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factures
    ADD CONSTRAINT factures_pkey PRIMARY KEY (id);


--
-- Name: fonctions fonctions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fonctions
    ADD CONSTRAINT fonctions_pkey PRIMARY KEY (id);


--
-- Name: investissements investissements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investissements
    ADD CONSTRAINT investissements_pkey PRIMARY KEY (id);


--
-- Name: langues langues_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.langues
    ADD CONSTRAINT langues_pkey PRIMARY KEY (id);


--
-- Name: localisations localisations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.localisations
    ADD CONSTRAINT localisations_pkey PRIMARY KEY (id);


--
-- Name: localites localites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.localites
    ADD CONSTRAINT localites_pkey PRIMARY KEY (id);


--
-- Name: news news_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_pkey PRIMARY KEY (id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: payouts payouts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payouts
    ADD CONSTRAINT payouts_pkey PRIMARY KEY (id);


--
-- Name: pays pays_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pays
    ADD CONSTRAINT pays_pkey PRIMARY KEY (id);


--
-- Name: personal_access_tokens personal_access_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personal_access_tokens
    ADD CONSTRAINT personal_access_tokens_pkey PRIMARY KEY (id);


--
-- Name: projet_traductions projet_traductions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projet_traductions
    ADD CONSTRAINT projet_traductions_pkey PRIMARY KEY (id);


--
-- Name: projet_valorisations projet_valorisations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projet_valorisations
    ADD CONSTRAINT projet_valorisations_pkey PRIMARY KEY (id);


--
-- Name: projets projets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projets
    ADD CONSTRAINT projets_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: secteurs secteurs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.secteurs
    ADD CONSTRAINT secteurs_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: personal_access_tokens uk20da9dko0my7s7jua8k6mmmpy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personal_access_tokens
    ADD CONSTRAINT uk20da9dko0my7s7jua8k6mmmpy UNIQUE (user_id);


--
-- Name: employes uk3v0uyo0bds0i1s553pjkiewvv; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employes
    ADD CONSTRAINT uk3v0uyo0bds0i1s553pjkiewvv UNIQUE (email);


--
-- Name: projet_traductions uk43mbbg3n9a5qi7bakq5po79bf; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projet_traductions
    ADD CONSTRAINT uk43mbbg3n9a5qi7bakq5po79bf UNIQUE (projet_id, langue);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: contrats uk7847wroq06orgoghi95cw1te8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contrats
    ADD CONSTRAINT uk7847wroq06orgoghi95cw1te8 UNIQUE (investissement_id);


--
-- Name: fonctions uk8ouyjabnsmu9erh3nu3vkgwbl; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fonctions
    ADD CONSTRAINT uk8ouyjabnsmu9erh3nu3vkgwbl UNIQUE (nom);


--
-- Name: personal_access_tokens ukao0wfeb7nwpitvjg8279rvw5q; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personal_access_tokens
    ADD CONSTRAINT ukao0wfeb7nwpitvjg8279rvw5q UNIQUE (token);


--
-- Name: contrats ukcmeibak060qc5ld5vhfnjvjuk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contrats
    ADD CONSTRAINT ukcmeibak060qc5ld5vhfnjvjuk UNIQUE (numero_contrat);


--
-- Name: contrats ukcqnay629o19dm4m3pdp7fiedy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contrats
    ADD CONSTRAINT ukcqnay629o19dm4m3pdp7fiedy UNIQUE (token_verification);


--
-- Name: projets ukdb7nw5ciymhq8u1s2slqcflx2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projets
    ADD CONSTRAINT ukdb7nw5ciymhq8u1s2slqcflx2 UNIQUE (slug);


--
-- Name: roles ukg50w4r0ru3g9uf6i6fr4kpro8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukg50w4r0ru3g9uf6i6fr4kpro8 UNIQUE (role);


--
-- Name: investissements ukg7uw81iy4ja6di9e90qo10re3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investissements
    ADD CONSTRAINT ukg7uw81iy4ja6di9e90qo10re3 UNIQUE (reference_externe_stripe);


--
-- Name: users ukow0gan20590jrb00upg3va2fn; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukow0gan20590jrb00upg3va2fn UNIQUE (login);


--
-- Name: factures ukprjs57l43v08g08jb7rn2v5yk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factures
    ADD CONSTRAINT ukprjs57l43v08g08jb7rn2v5yk UNIQUE (numero_facture);


--
-- Name: wallets uksswfdl9fq40xlkove1y5kc7kv; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT uksswfdl9fq40xlkove1y5kc7kv UNIQUE (user_id);


--
-- Name: factures ukt5bafct2g03u8u0lag0kbpafl; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factures
    ADD CONSTRAINT ukt5bafct2g03u8u0lag0kbpafl UNIQUE (dividende_id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: wallets wallets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT wallets_pkey PRIMARY KEY (id);


--
-- Name: projets fk1noiwcmrswe9xx0t3q2c70jqv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projets
    ADD CONSTRAINT fk1noiwcmrswe9xx0t3q2c70jqv FOREIGN KEY (porteur_id) REFERENCES public.users(id);


--
-- Name: projets fk1sn6bexm3j33wnfm45jbuat69; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projets
    ADD CONSTRAINT fk1sn6bexm3j33wnfm45jbuat69 FOREIGN KEY (secteur_id) REFERENCES public.secteurs(id);


--
-- Name: user_langues fk26e88boyydi2q6cejfc6gtnhi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_langues
    ADD CONSTRAINT fk26e88boyydi2q6cejfc6gtnhi FOREIGN KEY (langue_id) REFERENCES public.langues(id);


--
-- Name: projet_traductions fk63p5b6ur1sk6r5pa83l6fa54j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projet_traductions
    ADD CONSTRAINT fk63p5b6ur1sk6r5pa83l6fa54j FOREIGN KEY (projet_id) REFERENCES public.projets(id);


--
-- Name: transactions fk6hfmdkfrqurh132xwph8t1h4k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk6hfmdkfrqurh132xwph8t1h4k FOREIGN KEY (destinataire_wallet_id) REFERENCES public.wallets(id);


--
-- Name: projets fk7y2sah7yes4ycsxte3c9u310i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projets
    ADD CONSTRAINT fk7y2sah7yes4ycsxte3c9u310i FOREIGN KEY (site_id) REFERENCES public.localisations(id);


--
-- Name: investissements fk90xcl00erxj62maij5tm2bfco; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investissements
    ADD CONSTRAINT fk90xcl00erxj62maij5tm2bfco FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: personal_access_tokens fk92xukdupieae587377q5b6m78; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personal_access_tokens
    ADD CONSTRAINT fk92xukdupieae587377q5b6m78 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: localites fk94ols7m3yw3vvru251fyd668o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.localites
    ADD CONSTRAINT fk94ols7m3yw3vvru251fyd668o FOREIGN KEY (pays_id) REFERENCES public.pays(id);


--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: wallets fkc1foyisidw7wqqrkamafuwn4e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT fkc1foyisidw7wqqrkamafuwn4e FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: documents fkd0xfbae9f7m472njciridugp2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fkd0xfbae9f7m472njciridugp2 FOREIGN KEY (projet_id) REFERENCES public.projets(id);


--
-- Name: factures fkd52gwxgointglynl2v9das1he; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factures
    ADD CONSTRAINT fkd52gwxgointglynl2v9das1he FOREIGN KEY (investisseur_id) REFERENCES public.users(id);


--
-- Name: projet_valorisations fkd7bi3n8q08i6npyrg2v3mto87; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projet_valorisations
    ADD CONSTRAINT fkd7bi3n8q08i6npyrg2v3mto87 FOREIGN KEY (projet_id) REFERENCES public.projets(id);


--
-- Name: localisations fke4xskljen1okcealcy65pysvs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.localisations
    ADD CONSTRAINT fke4xskljen1okcealcy65pysvs FOREIGN KEY (localite_id) REFERENCES public.localites(id);


--
-- Name: employe_fonctions fkggmf3pwsh0jtvb1jcw07i7ac1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employe_fonctions
    ADD CONSTRAINT fkggmf3pwsh0jtvb1jcw07i7ac1 FOREIGN KEY (employe_id) REFERENCES public.employes(id);


--
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_langues fkjgc4fh4qy0ql15v2hp768fody; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_langues
    ADD CONSTRAINT fkjgc4fh4qy0ql15v2hp768fody FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: employe_fonctions fkjoskcph1rdimxgc4jadp4gi07; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employe_fonctions
    ADD CONSTRAINT fkjoskcph1rdimxgc4jadp4gi07 FOREIGN KEY (fonction_id) REFERENCES public.fonctions(id);


--
-- Name: contrats fkl6gts6lmyq2lpkw7n6ss7t91b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contrats
    ADD CONSTRAINT fkl6gts6lmyq2lpkw7n6ss7t91b FOREIGN KEY (investissement_id) REFERENCES public.investissements(id);


--
-- Name: users fklqc1yfb0yqnrd00aavx1v5svr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fklqc1yfb0yqnrd00aavx1v5svr FOREIGN KEY (localite_id) REFERENCES public.localites(id);


--
-- Name: dividendes fkm5pxys5qix0hmse47d8x4pfyv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dividendes
    ADD CONSTRAINT fkm5pxys5qix0hmse47d8x4pfyv FOREIGN KEY (investissement_id) REFERENCES public.investissements(id);


--
-- Name: notification fknk4ftb5am9ubmkv1661h15ds9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fknk4ftb5am9ubmkv1661h15ds9 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: investissements fko1tnlcr10jpicpfb1ghtd5hgm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investissements
    ADD CONSTRAINT fko1tnlcr10jpicpfb1ghtd5hgm FOREIGN KEY (projet_id) REFERENCES public.projets(id);


--
-- Name: factures fkq8ng83fsedrvs36pkx1ehwa1q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factures
    ADD CONSTRAINT fkq8ng83fsedrvs36pkx1ehwa1q FOREIGN KEY (dividende_id) REFERENCES public.dividendes(id);


--
-- Name: projets fkrx1n763f0w4j3volp8fi45y36; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projets
    ADD CONSTRAINT fkrx1n763f0w4j3volp8fi45y36 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--


