-- Galerie de photos additionnelles d'un projet, distincte du poster
-- principal (Projet.poster) qui reste l'image "épinglée" affichée en
-- vignette dans le catalogue et en hero sur la page détail.
CREATE TABLE projet_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projet_id BIGINT NOT NULL REFERENCES projets(id) ON DELETE CASCADE,
    url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_projet_photos_projet_id ON projet_photos(projet_id);
