CREATE TABLE contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    sujet VARCHAR(150) NOT NULL,
    message VARCHAR(3000) NOT NULL,
    statut VARCHAR(20) NOT NULL DEFAULT 'NOUVEAU',
    reponse VARCHAR(3000),
    repondu_par VARCHAR(150),
    date_envoi TIMESTAMP NOT NULL DEFAULT now(),
    date_reponse TIMESTAMP
);

CREATE INDEX idx_contact_messages_user_id ON contact_messages(user_id);
CREATE INDEX idx_contact_messages_statut ON contact_messages(statut);
