ALTER TABLE contact_messages
    ADD COLUMN hidden_for_user BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN hidden_for_admin BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE contact_replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_message_id BIGINT NOT NULL REFERENCES contact_messages(id) ON DELETE CASCADE,
    auteur_id BIGINT NOT NULL REFERENCES users(id),
    is_admin BOOLEAN NOT NULL,
    contenu VARCHAR(3000) NOT NULL,
    date_envoi TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_contact_replies_contact_message_id ON contact_replies(contact_message_id);

-- Préserve les réponses déjà enregistrées avant le passage au modèle de fil
-- de discussion (une seule réponse plate par message) en les recréant comme
-- premier ContactReply du fil, pour ne pas perdre l'historique déjà traité.
-- auteur_id référence le user_id du fil (faute d'avoir conservé l'ID de
-- l'admin qui avait répondu, seul son nom l'était dans repondu_par) — sans
-- incidence : c'est une reprise ponctuelle de données de test, is_admin=TRUE
-- suffit pour l'affichage correct côté frontend.
INSERT INTO contact_replies (contact_message_id, auteur_id, is_admin, contenu, date_envoi)
SELECT cm.id, cm.user_id, TRUE, cm.reponse, COALESCE(cm.date_reponse, cm.date_envoi)
FROM contact_messages cm
WHERE cm.reponse IS NOT NULL;
