CREATE TABLE fournisseurs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    statut_juridique VARCHAR(20) NOT NULL,
    raison_sociale VARCHAR(150),
    secteur_id BIGINT REFERENCES secteurs(id),
    ville VARCHAR(100) NOT NULL,
    pays VARCHAR(100) NOT NULL,
    telephone VARCHAR(30),
    email VARCHAR(191),
    description VARCHAR(2000),
    statut VARCHAR(20) NOT NULL DEFAULT 'EN_ATTENTE',
    date_soumission TIMESTAMP NOT NULL DEFAULT now(),
    date_validation TIMESTAMP,
    motif_rejet VARCHAR(500)
);

CREATE INDEX idx_fournisseurs_statut ON fournisseurs(statut);
CREATE INDEX idx_fournisseurs_ville ON fournisseurs(ville);
CREATE INDEX idx_fournisseurs_pays ON fournisseurs(pays);

CREATE TABLE articles_fournisseur (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fournisseur_id BIGINT NOT NULL REFERENCES fournisseurs(id) ON DELETE CASCADE,
    nom VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    prix NUMERIC(18,2) NOT NULL,
    unite VARCHAR(50) NOT NULL,
    disponible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_articles_fournisseur_fournisseur_id ON articles_fournisseur(fournisseur_id);

CREATE TABLE commandes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projet_id BIGINT NOT NULL REFERENCES projets(id),
    fournisseur_id BIGINT NOT NULL REFERENCES fournisseurs(id),
    montant_total NUMERIC(18,2) NOT NULL,
    statut VARCHAR(30) NOT NULL DEFAULT 'EN_ATTENTE_VALIDATION',
    date_commande TIMESTAMP NOT NULL DEFAULT now(),
    date_validation_admin TIMESTAMP,
    date_livraison TIMESTAMP,
    date_confirmation_reception TIMESTAMP,
    motif_rejet VARCHAR(500),
    motif_litige VARCHAR(1000)
);

CREATE INDEX idx_commandes_projet_id ON commandes(projet_id);
CREATE INDEX idx_commandes_fournisseur_id ON commandes(fournisseur_id);
CREATE INDEX idx_commandes_statut ON commandes(statut);

CREATE TABLE commande_lignes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commande_id BIGINT NOT NULL REFERENCES commandes(id) ON DELETE CASCADE,
    article_id BIGINT REFERENCES articles_fournisseur(id),
    libelle VARCHAR(150) NOT NULL,
    prix_unitaire NUMERIC(18,2) NOT NULL,
    quantite INTEGER NOT NULL,
    sous_total NUMERIC(18,2) NOT NULL
);

CREATE INDEX idx_commande_lignes_commande_id ON commande_lignes(commande_id);
