INSERT INTO secteurs (id, nom) VALUES
(1, 'AGRICULTURE'), (2, 'ENERGIE'), (3, 'IMMOBILIER'), (4, 'TECHNOLOGIE'),
(5, 'SANTE'), (6, 'EDUCATION'), (7, 'TOURISME'), (8, 'ALIMENTATION'),
(9, 'ENVIRONNEMENT'), (10, 'TRANSPORT'), (11, 'FINANCE'), (12, 'MINIER')